### ISSUE TITLE
NoMethodError: undefined method `fullname' for [:kind, nil]:Array

### ISSUE THREAD

**Issue by roback** [avinashbot/redd#41]
We have been getting the following error a few times in the last weeks. We're using `0.7.10`.

I have no idea what the cause behind this is. Perhaps it's just the Reddit API returning an unexpected response.

```
NoMethodError: undefined method `fullname' for [:kind, nil]:Array
  redd/clients/base/stream.rb:65:in `block (2 levels) in stream'
    yield thing if bset.enqueue?(thing.fullname)
  redd/clients/base/stream.rb:64:in `reverse_each'
    listing.reverse_each do |thing|
  redd/clients/base/stream.rb:64:in `block in stream'
    listing.reverse_each do |thing|
  redd/clients/base/stream.rb:58:in `loop'
    loop do
  redd/clients/base/stream.rb:58:in `stream'
    loop do
...
```

**Comment by avinashbot** [comment]
Hi! Sorry for the unbelievably long response time, I was working on `v0.8` and wanted to let you know once I released it, since it's a complete refresh over the old gem. Unfortunately that took a bit longer than expected and I ended up forgetting about the issue.

I'd recommend upgrading to `v0.8.0` and I'd be more than happy to assist with the upgrade. Otherwise, it does seem like a bizarre response from reddit or a problem with parsing the response. It looks like reddit is respoding with an object of type 'nil', which I've never seen before. Does it only happen occasionally?

**Comment by roback** [comment]
> Does it only happen occasionally?

Yes, we have only seen this error 12 times since January, so it hasn't bothered us that much.

We'll try out v0.8 when we get the time and see if that fixes things. Since it is a complete rewrite I suspect that it is unlikely this exact error will happen again :)
